---
title: Studio Self
timezone: UTC
collections:
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: projects
  values:
    layout: post
    thumbnail:
      image:
permalink: pretty
