const ACTIVE_CLASS = 'is-active'
const TRANSITION_DURATION = 200
const TRANSITION_EASING = 'easeInOutCubic'
const MAIN_ELEMENT_ID = 'main'
const SAVER_WAIT_DURATION = 90000

export {
  MAIN_ELEMENT_ID,
  ACTIVE_CLASS,
  TRANSITION_DURATION,
  TRANSITION_EASING,
  SAVER_WAIT_DURATION,
}
